repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args: ['--line-length', '99']
        language_version: python3
        additional_dependencies: ['click==8.0.4'] #https://github.com/psf/black/issues/2964#issuecomment-1080974737
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        args:
        -   --max-line-length=99
        -   --ignore=E501,E402,W503
        # E501: line too long (82 > 79 characters)
        # E402: module level import not at top of file
        # W503: line break before binary operator
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        always_run: true
        files: ^test_ # tests/  # or "^test_" if your test files start with 'test_'
